name: Widgetario release 21.03

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/21.03.yaml"
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@master

      - name: Build and push 21.03 Intel images
        working-directory: src
        run: |
          docker-compose -f docker-compose.yml -f build-21.03.yml -f build-21.03-amd64.yml build 
          docker-compose -f docker-compose.yml -f build-21.03.yml -f build-21.03-amd64.yml push

  build-linux-arm64:
    runs-on: [self-hosted, Linux, ARM64, docker]
    steps:
      - name: Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@master  

      - name: Build and push 21.03 ARM64 images
        working-directory: src
        run: |
          docker compose -f docker-compose.yml -f build-21.03.yml -f build-21.03-arm64.yml build --pull
          docker compose -f docker-compose.yml -f build-21.03.yml -f build-21.03-arm64.yml push

  push-manifests:
    runs-on: ubuntu-latest
    needs: ['build-linux-amd64', 'build-linux-arm64']
    steps:
      - name: Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@master 

      - name: Build and push 21.03 manifests
        working-directory: src
        run: |
          ./push-manifests-21.03.ps1        
        shell: pwsh