version: "3.7"

services:  
  gogs:
    image: widgetario/gogs:0.12.3
    build:
      context: ./gogs

  jenkins:
    image: widgetario/jenkins:2.319.1
    build:
      context: ./jenkins
  
  elasticsearch:
    image: widgetario/elasticsearch:7.10
    build: 
      context: ./elasticsearch
      args: 
        - ES_VERSION=7.10.2

  kibana:
    image: widgetario/kibana:7.10
    build: 
      context: ./kibana
      args: 
        - KIBANA_VERSION=7.10.2
        - NODE_TAG=10.23.1-alpine3.11
