services:

  products-db:
    image: widgetario/products-db:postgres
    build:
      context: db/postgres

  products-db-replicated:
    image: widgetario/products-db:postgres-replicated
    build:
      context: db/postgres-replicated

  products-api:
    image: widgetario/products-api:java
    build:
      context: products-api/java

  stock-api:
    image: widgetario/stock-api:golang
    build:
      context: stock-api/golang
  
  web:
    image: widgetario/web:dotnet
    build:
      context: web/dotnet
  
  web-v2:
    image: widgetario/web:dotnet-v2
    build:
      context: web/dotnet
      dockerfile: Dockerfile.v2