services:

  products-db:
    image: widgetario/products-db:postgres
    ports:
      - "5432:5432"
    networks:
      - app-net

  products-api:
    image: widgetario/products-api:java
    environment:
      - PRICE_FACTOR=1.5
    ports:
      - "8081:80"
    networks:
      - app-net
    depends_on:
      - products-db

  stock-api:
    image: widgetario/stock-api:golang
    ports:
      - "8082:8080"
    networks:
      - app-net
    depends_on:
      - products-db
  
  web:
    image: widgetario/web:dotnet
    environment:
      - StockApi:Url="http://stock-api/:8080/stock" 
    ports:
      - "8080:80"
    networks:
      - app-net
    depends_on:
      - products-api      
      - stock-api

networks:
  app-net: