services:

  products-db:
    image: widgetario/products-db:postgres
    build:
      context: db/postgres
    ports:
      - "5432:5432"
    networks:
      - app-net

  products-api:
    image: widgetario/products-api:dotnet
    build:
      context: products-api/dotnet
    ports:
      - "8081:80"
    networks:
      - app-net
    depends_on:
      - products-db

  stock-api:
    image: widgetario/stock-api:dotnet
    build:
      context: stock-api/dotnet
    ports:
      - "8082:80"
    networks:
      - app-net
    depends_on:
      - products-db
  
  web:
    image: widgetario/web:dotnet-serilog
    build:
      context: web/dotnet
    ports:
      - "8080:80"
    networks:
      - app-net
    depends_on:
      - products-api      
      - stock-api

networks:
  app-net: